# Generated by Django 5.2.17 on 2026-10-05 12:53

import apps.documents.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_number', models.CharField(max_length=64, unique=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('inspection_date', models.DateTimeField()),
                ('inspection_type', models.CharField(max_length=64)),
                ('notice_period_days', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_notifications', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_notifications', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.location')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='projects.project')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('notified', 'Notified'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='proposed', max_length=32)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assignments', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_assignments', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inspections.inspectionnotification')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=64, unique=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('requested_inspection_date', models.DateTimeField(blank=True, null=True)),
                ('discipline', models.CharField(max_length=64)),
                ('inspection_type', models.CharField(max_length=64)),
                ('inspection_level', models.CharField(blank=True, max_length=16)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16)),
                ('special_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('clarification_required', 'Clarification Required'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('ready_for_scheduling', 'Ready for Scheduling')], default='draft', max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.contract')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.location')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_requests', to='projects.project')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.purchaseorder')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inspectionnotification',
            name='inspection_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='inspections.inspectionrequest'),
        ),
        migrations.CreateModel(
            name='InspectionVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.CharField(max_length=64, unique=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='inspections.assignment')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.location')),
            ],
        ),
        migrations.CreateModel(
            name='InspectorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(blank=True, max_length=64)),
                ('employment_type', models.CharField(choices=[('employee', 'Employee'), ('contractor', 'Contractor')], default='contractor', max_length=32)),
                ('disciplines', models.JSONField(default=list)),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('years_of_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('geographic_location', models.CharField(blank=True, max_length=128)),
                ('coverage_areas', models.JSONField(blank=True, default=list)),
                ('travel_preferences', models.JSONField(blank=True, default=dict)),
                ('conflict_of_interest_declared', models.BooleanField(default=False)),
                ('performance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuing_body', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=128)),
                ('file', models.FileField(blank=True, upload_to='certificates/%Y/%m/', validators=[apps.documents.validators.validate_upload])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='inspections.inspectorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='inspections.inspectorprofile')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inspections.inspectorprofile'),
        ),
        migrations.CreateModel(
            name='ITP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itp_number', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('revision', models.CharField(default='A', max_length=32)),
                ('applicable_standard', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itps', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='inspectionnotification',
            name='itp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.itp'),
        ),
        migrations.CreateModel(
            name='ITPActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_number', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('intervention_type', models.CharField(choices=[('H', 'Hold Point'), ('W', 'Witness Point'), ('SW', 'Spot Witness'), ('M', 'Monitoring'), ('R', 'Document Review')], max_length=8)),
                ('relevant_drawing', models.CharField(blank=True, max_length=255)),
                ('applicable_standard', models.CharField(blank=True, max_length=255)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('itp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='inspections.itp')),
            ],
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.PositiveIntegerField()),
                ('equipment_tag', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('material_type', models.CharField(blank=True, max_length=128)),
                ('specification', models.CharField(blank=True, max_length=255)),
                ('drawing_reference', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit', models.CharField(max_length=32)),
                ('previously_inspected_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('requested_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.inspectionrequest')),
            ],
            options={
                'ordering': ['request', 'item_number'],
            },
        ),
        migrations.AddIndex(
            model_name='inspectionrequest',
            index=models.Index(fields=['project', 'status'], name='inspections_project_1ddd8c_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrequest',
            index=models.Index(fields=['request_number'], name='inspections_request_593e68_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['inspector', 'date'], name='inspections_inspect_224696_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('inspector', 'date')},
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['inspector', 'status'], name='inspections_inspect_a91c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['notification'], name='inspections_notific_54a26f_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionnotification',
            index=models.Index(fields=['project', 'status'], name='inspections_project_45408d_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionnotification',
            index=models.Index(fields=['notification_number'], name='inspections_notific_34fbcf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itpactivity',
            unique_together={('itp', 'activity_number')},
        ),
        migrations.AlterUniqueTogether(
            name='requestitem',
            unique_together={('request', 'item_number')},
        ),
    ]
