# Generated by Django 5.1.7 on 2026-09-29 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('approve', 'Approve'), ('reject', 'Reject'), ('submit', 'Submit'), ('lock', 'Lock'), ('unlock', 'Unlock')], max_length=32)),
                ('object_type', models.CharField(max_length=128)),
                ('object_id', models.CharField(max_length=64)),
                ('object_repr', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__0e78a5_idx'), models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_314539_idx'), models.Index(fields=['action', 'timestamp'], name='audit_audit_action_d7f04a_idx')],
            },
        ),
    ]
