# Generated by Django 5.2.17 on 2026-10-05 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=64)),
                ('tax_number', models.CharField(blank=True, max_length=64)),
                ('address', models.TextField(blank=True)),
                ('billing_address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='clients_cli_name_5ab7bc_idx'), models.Index(fields=['is_active'], name='clients_cli_is_acti_57c1e7_idx'), models.Index(fields=['client_code'], name='clients_cli_client__3e1ec5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('requester', 'Requester'), ('approver', 'Approver')], max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='clients.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['client', 'role'], name='clients_cli_client__85942f_idx')],
                'unique_together': {('user', 'client')},
            },
        ),
    ]
