# Generated by Django 5.2.17 on 2026-10-05 12:53

import apps.documents.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discipline', models.CharField(max_length=64)),
                ('version', models.CharField(default='1.0', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=128, unique=True)),
                ('calibration_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=64, unique=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_required', 'Revision Required'), ('approved', 'Approved'), ('issued', 'Issued')], default='draft', max_length=32)),
                ('scope', models.TextField(blank=True)),
                ('inspected_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('accepted_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('rejected_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('remaining_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('instruments_used', models.JSONField(blank=True, default=list)),
                ('narrative', models.TextField(blank=True)),
                ('deviations', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='inspections.inspectionvisit')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncr_number', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('requirement_reference', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=32)),
                ('proposed_corrective_action', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('verification', 'Verification'), ('closed', 'Closed'), ('waived', 'Waived')], default='open', max_length=32)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_ncrs', to=settings.AUTH_USER_MODEL)),
                ('inspection_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncrs', to='inspections.inspectionvisit')),
                ('itp_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.itpactivity')),
                ('responsible_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_ncrs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ncr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='reports.ncr')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_number', models.CharField(max_length=64, unique=True)),
                ('notes', models.TextField()),
                ('is_final', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('inspection_visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='release_notes', to='inspections.inspectionvisit')),
                ('released_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='released_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('content', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='reports.inspectionreport')),
            ],
            options={
                'ordering': ['-revision_number'],
                'unique_together': {('report', 'revision_number')},
            },
        ),
        migrations.AddField(
            model_name='ncr',
            name='report_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncrs', to='reports.reportrevision'),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=128)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('tolerance', models.CharField(blank=True, max_length=128)),
                ('result', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='reports.reportrevision')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=64)),
                ('answer', models.CharField(max_length=32)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_answers', to='reports.reportrevision')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', validators=[apps.documents.validators.validate_upload])),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('report_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.reportrevision')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=32)),
                ('schema', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='reports.inspectiontemplate')),
            ],
            options={
                'unique_together': {('template', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='template_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.templateversion'),
        ),
        migrations.AddIndex(
            model_name='inspectionreport',
            index=models.Index(fields=['inspection_visit', 'status'], name='reports_ins_inspect_f6daa9_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionreport',
            index=models.Index(fields=['report_number'], name='reports_ins_report__f1b2ae_idx'),
        ),
    ]
